version: '3.8'

services:
    node_docker:
        container_name: node_docker
        restart: always
        build:
            context: .
            dockerfile: ./docker/dev/Dockerfile.dev
            target: development
        environment:
            NODE_ENV: developer
        ports:
            - "${PORT_PUBLIC}:${PORT}"
        volumes:
            - './src:/usr/src/app/src'
        env_file:
            - .env
        command: npm run dev
        networks:
            - node-docker
        healthcheck:
            test: ["CMD", "sh", "-c", "wget localhost:${PORT_PUBLIC}/api/v1 -q -O - > /dev/null 2>&1 && wget localhost:${PORT_PUBLIC}/api/v1 -q -O - > /dev/null 2>&1"]
            interval: 60s
            timeout: 2s
            retries: 3            

networks:
    node-docker:
        driver: bridge