FROM redis:latest

RUN apt-get update && \
    apt-get install -y nano

COPY ./script/ /usr/local/bin/script/
COPY ./redis/redis.conf /usr/local/etc/redis/redis.conf

RUN chmod +x /usr/local/bin/script/start_redis.sh
RUN chmod +x /usr/local/bin/script/script_redis.sh
