version: "3.8"

services:
    service_student:
        container_name: service_student
        image: nguyentientai/class_fullstack:node-docker-taidev
        networks:
          - nginx-proxy       

    nginx-proxy:
      # image: nginx:latest
      container_name: nginx-proxy
      build:
          dockerfile: ./docker/dockerfile
          context: .
      restart: always
      depends_on:
          - service_student     
      env_file:
          - .env          
      networks:
        - nginx-proxy
      ports:
        - "${PORT_NGINX}:${PORT_NGINX}"
      volumes:
        - ./conf.d:/etc/nginx/conf.d:ro
        - ./snippets:/etc/nginx/snippets:ro
        - ./html:/usr/share/nginx/html:ro
        - ./assets:/usr/share/nginx/assets:ro
networks:
  nginx-proxy:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
